kubearchive/kubearchive

- .github/workflows/gitleaks.yml
- .github/workflows/static_code_analysis.yml
We hope to have upstream contributions from developers outside Red Hat. While I will add instructions for setting up open source gitleaks checking to the contributing guide, we need extra protection. So, I added a schedule to ensure that gitleaks runs against the repository regularly. For now, once a week should be sufficient. We can alter the schedule once the pace of development increases.
Signed-off-by: cbeer <cbeer@redhat.com>
> fix(KAR-26): add gitleaks scanning

- charts/kubearchive/templates/_helpers.tpl
- charts/kubearchive/templates/api_server.yaml
- charts/kubearchive/values.yaml
- pkg/observability/trace.go
OpenTelemetry instrumentation will only start if the environment variable `KUBEARCHIVE_OTEL_ENABLED=true`.
closes #36
> otel instrumentation only starts when environment variable is set

- .github/workflows/renovate.yml
Configure renovate to run as kubearchive-renovate github app. The action is configured to run weekly on Monday at ~8:15 UTC
closes #45
> add github action for renovate

- .gitignore
- DEVELOPMENT.md
- charts/kubearchive/crds/cert-manager.yaml
- charts/kubearchive/templates/api_server.yaml
- charts/kubearchive/templates/certificates.yaml
- cmd/api/main.go
- test/integration/integration_test.go
* Add the cert-manager v1.15 version to helm crds
* Add a template file that generates a CA cert and a certificate for the API
* Change the API server to mount the certificate and use it
* Add instructions to get the CA certificate to query the API with curl
Closes #58
> Add cert-manager for API server

- .github/workflows/static_code_analysis.yml
- .golangci.yml
- cmd/api/auth/authn_test.go
- cmd/api/main_test.go
- cmd/api/routers/routers_test.go
- cmd/sink/main.go
bodyclose       - enforce that http response bodies get closed
containedctx  - enforce that contexts do not get placed as fields in a struct
fatcontext       - enforce that contexts do not get nested in loops
gofmt               - enforce the golang code style
nilerr                - enforce that an error is not returned as nil if the code checks the there error is not actually nil
usestdlibvars  - detect values that can be replaced with vars/consts from go standard library
wastedassign - detect vars that are reassigned and the new value is never used
Also fix code so that it passes all of the lint checks
> add linters to golangci-lint

- .github/workflows/static_code_analysis.yml
- .gitignore
- .yamllint.yml
- charts/kubearchive/templates/api_server/api_server.yaml
- charts/kubearchive/templates/api_server_source.yaml
- charts/kubearchive/templates/namespace.yaml
- charts/kubearchive/templates/role.yaml
- charts/kubearchive/templates/role_binding.yaml
- charts/kubearchive/templates/service_account.yaml
- charts/kubearchive/templates/sink/sink.yaml
Replaces https://github.com/kubearchive/kubearchive/pull/69.
> Run helm to generate templated files for yamllint.

- charts/kubearchive/templates/role.yaml
- charts/kubearchive/templates/role_binding.yaml
- charts/kubearchive/templates/sink/service_account.yaml
create a service account for kubearchive-sink. Also create a role and a role and role binding so that the kubearchive-sink service account has permissions to get, list, and delete resources that kubearchive has been configured to archive.
closes #61
> create service account for kubearchive-sink

- DEVELOPER_RESOURCES.md
- DEVELOPMENT.md
- charts/kubearchive/templates/api_server/role.yaml
- charts/kubearchive/templates/api_server/role_binding.yaml
- charts/kubearchive/templates/api_server/service_account.yaml
- charts/kubearchive/values.yaml
* Include permissions for the `kubearchive-api-server` service account to create TokenReview objects.
* Include a new service account called `kubearchive-privileged-user` with view permissions
* Update `DEVELOPMENT.md`
> Fix helm chart to include tokenreview permissions

- DEVELOPMENT.md
- charts/kubearchive/templates/api_server/api_server.yaml
- charts/kubearchive/templates/api_server/service_account.yaml
- charts/kubearchive/templates/certificates.yaml
- charts/kubearchive/templates/namespace.yaml
- charts/kubearchive/templates/operator/auth_proxy_service.yaml
- charts/kubearchive/templates/operator/leader_election_role.yaml
- charts/kubearchive/templates/operator/leader_election_role_binding.yaml
- charts/kubearchive/templates/operator/monitor.yaml
- charts/kubearchive/templates/operator/operator.yaml
- charts/kubearchive/templates/operator/service_account.yaml
- charts/kubearchive/templates/service_account.yaml
- charts/kubearchive/templates/sink/service_account.yaml
- charts/kubearchive/templates/sink/sink.yaml
Create kubearchive namespace outside of the templates with the `--create-namespace` option.
Remove the namespace of the kubearchive resources as they are going to be installed in the namespace indicated with `-n` option that now is `kubearchive`
> Install helm chart in kubearchive namespace

- .github/workflows/renovate.yml
- renovate.json
- renovate will check osv.dev for security vulnerabilities 
- renovate will run daily at 8:15 UTC instead of weekly on Monday at 8:15 UTC. By default, renovate will only create 2 PRs at most per run so we will not be overwhelmed with renovate PRs
- renovate will not use sematic commit names in PRs and commits since we're not using them
Resolves #120 
Resolves #131
> update renovate configuration

- cmd/operator/internal/controller/kubearchiveconfig_controller.go
- cmd/operator/main.go
- docs/modules/ROOT/pages/configuration/kubearchiveconfig.adoc
Resolves https://github.com/kubearchive/kubearchive/issues/136.
> Get the real plural name from the CRD, rather than blindly appending 's'.

- pkg/database/database.go
Related to #171 
```release-note
NONE
```
This PR stops the sink from writing timestamps for `created_at` and `updated_at` so that the database will handle it
> sink lets database add created_at and update updated_at timestamps in resource table

- charts/kubearchive/templates/sink/sink.yaml
- charts/kubearchive/values.yaml
- cmd/operator/internal/controller/kubearchiveconfig_controller.go
- cmd/sink/client.go
- cmd/sink/jsonPath/jsonPath.go
- cmd/sink/main.go
Fixes #191 
```release-note
NONE
```
The operator grants the sink's ServiceAccount permissions to delete the resource type(s) being watched. When deploying kubearchive, the user can specify a JSON Path that, if it returns a value when applied to a kubernetes object, will cause the sink to delete the kubernetes object from the cluster.
> sink deletes k8s objects when json path returns a value

- renovate.json
Fixes #201 
```release-note
NONE
```
* The configuration read was from the `main` branch, which did not contain the `goModTidy` option. I had to use the parameter `configurationFile` to make the changes on this branch matter. I removed it after testing because we don't need to specify it.
* This was tested at https://github.com/kubearchive/kubearchive/pull/245 by running manually the Renovate workflow from a branch with these changes.
> Enable 'go mod tidy' for renovate

- charts/kubearchive/templates/api_server/api_server.yaml
- charts/kubearchive/templates/api_server/certificates.yaml
Fixes #91 
```release-note
NONE
```
This PR is the first of several that we should create if we agree to go on with the usage of the [required](https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-required-function) helm keyword.
The main goal is to prevent introducing typos in the templated variables of the templates in the charts.
The required should be introduced in non-mandatory fields (AFAIK, the only field that files an error with `helm lint --strict` if it's not provided is `.metadata.name`) that don't use `tpl` function. This way we will prevent having empty values after `helm template` by mistake.
With the usage of `tpl` the `required` function is not needed because if the variable to be templated not exist, it files an error.
> Add required helm kw to api templates

- test/integration/integration_test.go
Fixes #127 
```release-note
NONE
```
* Today I merged #251 but I missed that the schema for KubeArchiveConfig changed in the last days. The integration tests now fail because of that. I'm submitting this to fix it.
> Fix integration tests

- cmd/api/main.go
- cmd/sink/main.go
- pkg/observability/trace.go
Resolves #207 
```release-note
NONE
```
* The change has been made in code even if `OTEL_SERVICE_NAME` can be set because the value of the name is more a constant than a variable, so it made more sense to me to add it within the code.
* I can extract the name to a variable at the top of the file instead, but hardcoding it on the function didn't look crazy to me.
> Set service name for telemetry

- DEVELOPMENT.md
- cmd/operator/internal/controller/kubearchiveconfig_controller.go
- cmd/sink/main.go
- hack/quick-install.sh
Fixes #232 
The after the sink deletes a kubernetes object, it will update the entry in the database for that resource with timestamp of when the resource was deleted. Bumped the version of knative-eventing to v1.15.0 so that the operator can apply a filter to all ApiServerSources so that they do not send delete type cloudevents.
```release-note
NONE
```
- knative-eventing version bump `v1.14.3` -> `v1.15.0`
- operator applies a filter to ApiServerSources so they do not send `delete` type cloudevents
To test:
- run `hack/quick-install.sh`
- initialize the database
- run `kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml`
- run
```bash
kubectl apply -f - << EOF
---
apiVersion: kubearchive.kubearchive.org/v1alpha1
kind: KubeArchiveConfig
metadata: …
```
> sink does not try to delete k8s objects twice

- charts/kubearchive/templates/test/kac.yaml
- docs/modules/ROOT/pages/configuration/kubearchiveconfig.adoc
- test/integration/integration_test.go
Resolves #285
```release-note
NONE
```
> Operator creates invalid cel expressions in KubeArchiveConfig.

- charts/kubearchive/templates/operator/operator.yaml
- cmd/operator/main.go
Resolves #236
```release-note
NONE
```
Note that this PR only includes changes to add instrumentation to the the operator.  The operator-sdk itself has no instrumented library, so this PR just lays the groundwork for work to be done in https://github.com/kubearchive/kubearchive/issues/307.
As a result, the changes here are minimal.
> Implement OpenTelemetry in the operator.

- go.mod
- go.sum
- pkg/database/database.go
- test/integration/integration_test.go
Fixes #242 
```release-note
NONE
```
- Added retries to the database connection using the library: [retry-go](https://github.com/avast/retry-go)
- The library uses, by default, exponential back-off.
- Added an integration test to check the retry mechanism.
- Manually tested deploying kuberarchive from scratch (no restart in the sink and neither in the API)
- Manually tested write in the database after retries + connection.
> add retries to the database connection

- charts/kubearchive/templates/api_server/api_server.yaml
- cmd/api/main.go
- test/integration/integration_test.go
Solves a bug introduced in #340 
```release-note
NONE
```
* The first test that makes sure that every deployment was OK was too fast, as well as the `rollout status` that happens on the `hack/quick-install.sh` script. This is why this could pass CI.
* I put the cache environment variables get operator before the database, so it crashes before it starts with the retries that connect to the database. I think the retries to the database make the Deployment seem OK, then crash when it connected and got to the cache configuration.
* Also introduced a check for the retry on the integration test, because the general error was not being checked.
* I think these problems will be mitigated by #305
> Fix envvar for cache expiration

- cmd/sink/main.go
pass ctx to context.WithTimeout so that when the sink creates otel spans, they look right
Resolves #301 
```release-note
NONE
```
> reuse context when setting timeouts

- charts/kubearchive/templates/_helpers.tpl
Resolves #388
```release-note
NONE
```
> Fix POSTGRES_URL env value in helm chart templates

- database/ddl-resource.sql
Explicit the database where trigger_set_timestamp function is located
Fixes #384 
```release-note
NONE
```
> Fix error of function not found in DDL

- charts/kubearchive/templates/_helpers.tpl
- docs/modules/ROOT/pages/configuration/enable-observability.adoc
- pkg/observability/trace.go
Resolves #233 
```release-note
Now KubeArchive supports different telemetry modes of operation using `KUBEARCHIVE_OTEL_MODE`. This variable replaced `KUBEARCHIVE_OTEL_ENABLED`.
```
> Introduce telemetry modes

- cmd/api/discovery/apiresources.go
- cmd/api/discovery/apiresources_test.go
- cmd/api/main.go
- cmd/api/routers/routers.go
- cmd/api/routers/routers_test.go
Resolves #195 
```release-note
NONE
```
* Changed `apiResource` to `apiResourceKind` and store just the string, there is no need to pass around the object and then reserializing it just to get the `Kind`.
* Moved `getApiResourceKind` to the `discovery` package so its closer to its counterpart (that sets the context property).
> Cache discovery endpoint calls

- cmd/sink/filters/filters.go
- cmd/sink/main.go
Resolves #337 
```release-note
NONE
```
The sink now checks if the received cloudevent's type is 'delete'. If it is, the sink checks if the object contained in the cloudevent meets the criteria for archiveOnDelete. If the object meets that criteria, the object is written to the database. If the object does not meet the criteria, the sink ignores the message. If the cloudevent's type is not 'delete', the sink handles the cloudevent normally.
> sink can archive objects when they are deleted

- docs/modules/ROOT/pages/reference/database.adoc
- integrations/database/postgresql/kubearchive.sql
Resolves #441 
```release-note
NONE
```
This PR only add indexes in PostgreSQL. I'll open a new issue to add it to MariaDB and MySQL.
Tests:
* Using a dataset of ~1600 entries and EXPLAIN ANALYZE utility from PostgreSQL.
> Create indexes in the database

- cmd/sink/filters/filters.go
The operator places the global filters in the ConfigMap under the key kubearchive not _global
resolves #524 
Resolves #
```release-note
NONE
```
> Sink looks for global filters under the key kubearchive instead of _global

- cmd/api/main.go
- cmd/api/main_test.go
- cmd/api/pagination/pagination.go
- cmd/api/routers/routers.go
- cmd/api/routers/routers_test.go
- go.mod
- integrations/database/postgresql/kubearchive.sql
- pkg/database/database.go
- pkg/database/database_test.go
- pkg/database/fake/database_generated.go
- pkg/database/fake/database_generated_test.go
- pkg/database/mariadb.go
- pkg/database/postgresql.go
Resolves #226 
```release-note
Endpoints that retrieve collections of resources support pagination similar to the Kubernetes API.
```
* I decided to go with ORDER BY because I keep reading (with proof) that LIMIT + OFFSET is slow and its best to do this approach (known as keyset pagination).
* We talked about adding `remainingItems` in the List response. That will be handled in a separate issue (https://github.com/kubearchive/kubearchive/issues/531).
To test:
```
export KO_DOCKER_REPO="kind.local"
kind create cluster
bash hack/quick-install.sh
cat table.sql | kubectl exec -n postgresql -it pods/kubearchive-1 -- psql kubearchive
kubectl create role view-jobs --verb=get --resource=jobs,jobs/status --dry-run=client -o yaml | kubectl apply -f -
kubectl create rolebinding view-jobs --role …
```
> Add pagination support

- charts/kubearchive/templates/sink/sink.yaml
- cmd/sink/filters/filters.go
Resolves #524 
```release-note
NONE
```
Instead of using a hardcoded string for the global filters key, it can be obtained from an environment variable
> use environment variable to get the key for global filters

- cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go
- cmd/sink/filters/filters.go
- cmd/sink/filters/filters_test.go
- cmd/sink/filters/testdata/cm.yaml
- cmd/sink/main.go
- pkg/cel/cel.go
Resolves #526 
```release-note
NONE
```
* My original intention was to refactor the code so global and local are treated in the same way and then do "namespace filters" + "global filters". However I found this approach in which we keep treating global filters in the same way. I will probably open an issue to refactor it. I think making this work has more priority than refactoring.
> Sink now applies global filters as well

- cmd/api/auth/authn_test.go
- cmd/api/auth/authz_test.go
- cmd/api/discovery/apiresources_test.go
- cmd/api/main.go
- cmd/api/main_test.go
- cmd/api/routers/routers_test.go
- go.mod
- go.sum
Related to #527 527
```release-note
NONE
```
* The current instrumentation package for gin does not provide metrics, I'm changing it to one that does.
* The current instrumentation used is deprecated and has no maintainer: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/6190
> Change API Gin metrics package

- .github/workflows/renovate.yml
- renovate.json
Resolves #597 
```release-note
NONE
```
- I had to move the rule requiring 2 approvals on PRs into its own ruleset, so that `kubearchive-renovate` can automerge its own PRs without being able to bypass the CI checks.
> renovate will automerge PRs if CI checks pass

- cmd/api/pagination/pagination.go
- cmd/api/pagination/pagination_test.go
- cmd/api/routers/routers.go
- go.mod
- integrations/database/postgresql/install.sh
- integrations/database/postgresql/kubearchive.sql
- pkg/database/database.go
- pkg/database/database_test.go
- pkg/database/fake/database_generated.go
- pkg/database/postgresql.go
Resolves #586 
```release-note
Now KubeArchive returns resources by creationTimestamp in descending order (new first)
```
* The query gets a little slower in the big dataset because the DESC makes the filter remove more rows.
* Bumped CloudNative PG to 1.24.1 to PostgreSQL so it defaults to PostgreSQL v17.
* `BIGSERIAL` is not a true type, so its not reflected directly here. It is translated to a BIGINT and a series of sequence statements that make the thing autoincrement on insert.
* To test download and load 500.txt into the database, then run:
[500.txt](https://github.com/user-attachments/files/17554742/500.txt)
```
curl -s --cacert ca.crt -H "Authorization: Bearer $(kubectl create token default)" "https://localhost:8081/api/v1/pods?limit=100" | jq -r '.items[] | …
```
> Fix result ordering

- cmd/api/auth/authz.go
- cmd/api/auth/authz_test.go
- cmd/api/main.go
- cmd/api/pagination/pagination.go
- cmd/api/pagination/pagination_test.go
- cmd/api/routers/routers.go
- cmd/api/routers/routers_test.go
- integrations/database/postgresql/README.md
- pkg/database/database.go
- pkg/database/database_test.go
- pkg/database/fake/database_generated.go
- pkg/database/fake/database_generated_test.go
- pkg/database/mariadb.go
- pkg/database/postgresql.go
- pkg/database/query.go
- test/integration/integration_test.go
Resolves #539
```release-note
Add new endpoints for the retrieval of log URLs
```
I've included a new file called `query.go` in the `database` package with helper functions to encapsulate the logic for parsing the sql row results into structs or primitive data.
All the queries (new and old) are using this new functions.
There is a new interface `DBParamParser` to be implemented in the different drivers for transforming arrays into the allowed parameters for parametrized statements. This way we allow having queries of the type `SELECT * FROM ... WHERE key IN ?` being `?` a set of elements of undefined length.
The endpoints return 404 when the resource doesn't exist in the database.
For testing, you can run the integration tests locally, check the namespace used for the generated data and …
> Retrieve log urls

- .golangci.yml
- cmd/api/main.go
- cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go
- cmd/operator/internal/controller/kubearchiveconfig_controller.go
- cmd/sink/filters/filters.go
- hack/get-next-version.go
- pkg/observability/trace.go
Resolves #638 
```release-note
NONE
```
The following `govet` analyzers are now enabled:
- the default set of `govet` analyzers (were already enabled before this PR)
- loopclosure: Check references to loop variables from within nested functions
- nilness: Check for redundant or impossible nil comparisons
- shadow: Check for possible unintended shadowing of variables
The following linters are now enabled:
- nilnil: Checks that there is no simultaneous return of nil error and an invalid value
Made some fixes so that all `golangci-lint` linters pass
> enable additional checks in `golangci-lint`

- go.mod
- go.sum
- pkg/database/connection.go
- pkg/database/database.go
- pkg/database/database_test.go
- pkg/database/query.go
Resolves #634 
```release-note
NONE
```
I kept the queryPerformer struct because of the variadic args handled with the `DBParamParser` interface of the `paramQuery` struct.
I also used string instead of `sql.RawBytes` (an alias of `[]byte`) because its usage is discouraged given that some drivers override its value after the `rows.Next()` execution.
More info about this on:
* https://github.com/DATA-DOG/go-sqlmock/issues/176
* https://jmoiron.github.io/sqlx/#query
> Add sqlx for structscan support

- go.mod
- go.sum
- test/integration/integration_test.go
Resolves #630
```release-note
NONE
```
I've added retries on the log url retrieval because if there aren't, even though the cronjob are archived the pods could not be so the log urls could be missing.
> Add log url retrieval integration test

- charts/kubearchive/templates/eventing/brokers.yaml
- charts/kubearchive/templates/sink/trigger.yaml
- cmd/operator/internal/controller/kubearchiveconfig_controller.go
- hack/quick-install.sh
Related #240 
```release-note
cloudevent delivery is retried up to five times 
```
KubeArchive uses a knative eventing broker to receive cloudevents from ApiServerSource and uses a knative eventing trigger to subscribe the sink to all events from the broker. The broker is configured to retry the delivery of cloudevents if the initial delivery fails. If all retries fail, the broker sends the cloudevent an other broker so that the cloudevents are not lost.
I replaced `eventing-core.yaml` with `eventing.yaml` in `hack/quick-install.sh` because `eventing.yaml` is `eventing-core.yaml` plus `in-memory-channel.yaml` and `mt-channel-broker.yaml` both of which need to be installed for the brokers to work.
> use knative brokers to handle event delivery

- cmd/operator/internal/controller/kubearchiveconfig_controller.go
Resolves #589 
```release-note
fix bug where operator uses the wrong service name for the sink when deployed in a namespace that is not kubearchive
```
make sure that the operator will use the name `kubearchive-sink` even if KubeArchive is not deployed in the `kubearchive` namespace
> fix how operator determines sink name

- cmd/sink/logs/logs.go
- cmd/sink/main.go
- integrations/database/mariadb/kubearchive.sql
- integrations/database/postgresql/kubearchive.sql
- pkg/database/database.go
- pkg/database/facade/inserter.go
- pkg/database/fake/database_generated.go
- pkg/database/fake/database_generated_test.go
Resolves #689 
```release-note
add json_path column to the log_url table
sink writes the value for LOG_URL_JSONPATH from the logging ConfigMap to the json_path column for the log_url table
```
UrlBuilder stores the value for `LOG_URL_JSONPATH` from the logging ConfigMap. Sink calls the `UrlBuilder.GetJsonPath()` method when writing log urls to the database.
> add json_path to log_url table

- go.mod
- go.sum
Resolves #716 
```release-note
upgrade to golang.org/x/crypto v0.31.0 to mitigate CVE-2024-45337
```
[CVE-2024-45337](https://github.com/advisories/GHSA-v778-237x-gjrc) was published for golang.org/x/crypto versions < v0.31.0. The fix is upgrade to a version >= v0.31.0
> update to golang.org/x/crypto v0.31.0

- .github/workflows/go_test_integration.yml
- cmd/api/logging/logging.go
- hack/quick-install.sh
- test/integration/integration_test.go
Resolves #740 
```release-note
NONE
```
Fixes:
1. Timeout on log retrieval. Due to the needed time for the logs to get to splunk, the total time of the test need to be increased. By default it was 10 minutes and I extended it to 30 minutes (I experienced failures with 15 and 20 minutes). 
2. The timeout on the pagination test is addressed by increasing the number of retries from 30 to 60
3. The timeout on the deployment of knative-eventing in the installation part has been extended from 30s to 50s.
4. Included 3 retries to the port-forward operation that sometimes failed.
> Fix timeout errors in integration tests

- cmd/sink/main.go
- pkg/database/database.go
- pkg/database/fake/database_generated.go
- pkg/database/fake/database_generated_test.go
Resolves #720
```release-note
Fixed bug where KubeArchive crashed under some circumstances and fixed a bug where KubeArchive could delete all logs related to a resource.
```
Databases.WriteUrls checks if k8sObj is nil If this condition is true, it returns an error and
does not perform any database transactions. sink.writeLogs checks if len(urls) == 0 and logs
that no urls were generated and does not call Database.WriteUrls when this condition is true
> Database.WriteUrls does not transact with invalid arguments

- docs/modules/ROOT/pages/getting-started/installation.adoc
- integrations/database/postgresql/postgres.yaml
- pkg/database/postgresql.go
Resolves #755 
```release-note
KubeArchive now requires PostgreSQL databases to be protected with TLS. It can be with a self-signed certificate as the certificate is not verified, just required.
```
> Set sslmode as required for PostgreSQL

- cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go
- cmd/operator/api/v1alpha1/kubearchiveconfig_webhook_test.go
- cmd/operator/main.go
Resolves #749 
```release-note
NONE
```
Replaced webhook.Validator with webhook.CustomValidator
Replaced webhook.Defaulter with webhook.CustomDeafulter
Renamed private method validateCELExpressions to validateKAC so it can also allocate the name validation
to avoid having this piece repeated.
Everything was done by following the kubebuilder docs  of the webhook implementation - https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation
With this effort unit tests were also added for the custom defaulter and validator
> Fix deprecated usage of Defaulter and Validator webhooks

- test/integration/integration_test.go
Resolves #752
```release-note
NONE
```
* Replaced `echo` by `sleep` so the messages have some time to get to the Sink. I think that may be a problem.
* Added `deleteWhen` so the pods from the test get removed and we avoid "too many files errors".
> Integration tests improvements

- pkg/database/connection.go
- pkg/database/database.go
Resolves #753 
```release-note
KubeArchive Sink component now fail if it can't connect to the database.
```
* The release notes just mention the sink because the API was failing before due to the ready endpoint, so from the user perspective the sink wasn't failing correctly but the API did (but for another reason).
> Sink and API now fail on DB startup error

- cmd/sink/routers/routers.go
- cmd/sink/routers/routers_test.go
- cmd/sink/server/server.go
- config/templates/sink/sink.yaml
Resolves #306 
```release-note
NONE
```
The readiness endpoint checks if the sink can connect to the database AND the Kubernetes API. Since the dynamic client does not have any kind of connection check method, the sink instead tries to list the ConfigMaps in the namespace it is deployed in (which it should always have the permissions to do)
> add liveness and readyness endpoints to the sink

- cmd/api/routers/routers.go
- cmd/api/routers/routers_test.go
- docs/modules/ROOT/pages/reference/api.adoc
- pkg/database/database.go
- pkg/database/database_test.go
- pkg/database/facade/filter.go
- pkg/database/fake/database_generated.go
- pkg/database/fake/database_generated_test.go
- pkg/database/labels.go
- pkg/database/mariadb.go
- pkg/database/postgresql.go
Resolves #567
```release-note
KubeArchive now supports the parameter `labelFilter` in most of its endpoints, see the documentation for more information.
```
Created a separate issue to address and test the `annotations` filters in https://github.com/kubearchive/kubearchive/issues/784
The filters are only implemented in PostgreSQL. Created a separate PR to address the changes for MariaDB: https://github.com/kubearchive/kubearchive/issues/785
I've attached a [queries.txt](https://github.com/user-attachments/files/18885958/queries.txt) (because Github doesn't allow attaching `SQL` files) with several queries and the outcomes with the different filters over 7M registries in the resources table.
Those queries made my decission to choose over one implementation of the filter or another given …
> Add label filters

- integrations/database/postgresql/kubearchive.sql
Resolves #848 
```release-note
NONE
```
I've ensured that the change in the schema is the same done by pg_dump tool.
Now the deletion doesn't need the `CASCADE` instruction but the `TRUNCATE` statement does.
PostgreSQL doesn't allow the `ON TRUNCATE CASCADE`.
> Add ON DELETE CASCADE to log_url FK

- cmd/sink/routers/result.go
- cmd/sink/routers/routers.go
- cmd/sink/routers/routers_test.go
- cmd/sink/routers/testdata/CE-not-k8s.json
- cmd/sink/routers/testdata/CE-pod-does-not-exist.json
- pkg/database/fake/database_generated.go
- pkg/database/fake/database_generated_test.go
Resolves #779, related to #814
```release-note
Now KubeArchive retries to process resource updates if a failure happens.
```
if the sink fails to write the resource or log urls from a cloud event to the database or if the sink fails to delete
the resource from the cluster, the sink will respond with an http 500 response. This will allow senders of Cloud
Events to respond to cloud event delivery failure. The exception to this is when the payload of the Cloud Event
is not a kubernetes resource. In this case a 422 response is sent.
> sink sends proper http response based on processing of a cloud event

- cmd/operator/main.go
- go.mod
- go.sum
Resolves #830 
```release-note
NONE
```
> Fix operator client to only cache kubearchive-namespaced resources.

- cmd/operator/internal/controller/kubearchiveconfig_controller.go
- test/integration/integration_test.go
- test/integration/logging_test.go
- test/integration/operator_test.go
- test/integration/pagination_test.go
- test/main.go
Resolves #780
```release-note
NONE
```
ApiServerSource requires resources to run successfully.  These changes take that into account. If at any point reconcile finds there are no resources to give to ApiServerSource, then the existing ApiServerSource is deleted.  It will be recreated the next time reconcile runs and has resources.
> Support empty KubeArchiveConfig.

- cmd/operator/internal/controller/kubearchiveconfig_controller.go
- cmd/sink/routers/result.go
- cmd/sink/routers/routers.go
- cmd/sink/routers/routers_test.go
- test/integration/pagination_test.go
Resolves #880, Related to #870 
```release-note
Fixed a bug where KubeArchive rejected resource updates leading to a performance issue
```
Follow knative-eventing spec by sending http 202 for successfully processed cloud events and remove response body from
the http response. 
https://github.com/knative/specs/blob/main/specs/eventing/data-plane.md#event-acknowledgement-and-delivery-retry
Add checks to TestPagination to make sure that TestPagination to make sure the sink-filters
ConfigMap and the ApiServerSource are ready before creating Pods.
Add check to the sink to make so that it can properly handle receiving a Cloud Event that matches a `DeleteWhen` CEL expression when the resource has already been deleted. The sink will see if the resource exists on the cluster and if it does not, it …
> Speed up integration test

- test/integration/logging_test.go
Resolves #905
```release-note
NONE
```
Splunk has issues with the logs for the container `second` because it seems like the pod gets deleted too quickly. For now the fix is removing the `deleteWhen` clause in the test, but a more robust change maybe implemented later
> remove deleteWhen so splunk correctly stores logs for pods with multiple containers

- .github/workflows/go_test_integration.yml
- .gitignore
- test/integration/integration_test.go
- test/integration/logging_test.go
- test/integration/pagination_test.go
- test/integration/run.sh
- test/main.go
Resolves #866
```release-note
NONE
```
`TestEmptyKAC`, `TestNonEmptyKAC`, and `TestDatabaseConnection` cannot be run in parallel. `TestEmptyKAC` and `TestNonEmptyKAC` cannot be run in parallel because they are affected by KACs created by other tests. `TestDatabaseConnection` cannot be run in parallel because messing with the api server and sink database connections affect other tests.
The code to port forward the api server and run the log generators has been modified to allow each to be called concurrently. Functions that write to stdout or stderr have been updated to call `t.Log` or `t.Log`f to make it easier to understand which test is printing what output.
Helper functions that write to stdout or stderr now call `t.Helper` to register themselves as helper functions to make tracing …
> run all integrations tests in parallel

- test/integration/run.sh
Resolves #917 
```release-note
NONE
```
test/integration/run.sh needs to set `set -o pipefail` so that if the `go test` command fails, the integration test action reports as failed. The script saves the `go test` return code, generates the summary of the action, then exits the script with the saved return code
> integration test action should fail when go test cmd fails

- .editorconfig
- integrations/database/postgresql/kubearchive.sql
Resolves #901 
```release-note
NONE
```
There is a cosmetic change of a tab to spaces that was done automatically by `pg_dump`.
I'm not sure why there was a tab instead of a set of spaces previously.
To prevent further errors like this, I've added the change suggested by Sam to get the IDE configured to do spacing instead of tabbing in the SQL files.
> Increase the work_mem parameter from 4MB (default) to 64MB

- test/integration/operator_test.go
Resolves #968
```release-note
NONE
```
> Fix test TestGlobalAndLocalKAC to clean up global KAC resource.

- pkg/cel/cel.go
- pkg/cel/cel_test.go
Resolves #959
```release-note
Add now() CEL extension, which returns the current timestamp.
```
> Add now() function for CEL expressions.

- docs/modules/ROOT/pages/design/database-interface.adoc
- docs/modules/ROOT/pages/integrations/database.adoc
- pkg/database/facade/filter.go
- pkg/database/mariadb.go
- pkg/database/postgresql.go
- pkg/database/reader.go
- pkg/database/reader_test.go
Resolves #902
```release-note
NONE
```
Still in draft to:
Check the specific last commit to see the actual changes in the filter.
The idea is that for the "complex" filters we allow to pass a WhereClause with the kind, apiversion and namespace (if applies) filters of the main query so it can be attached to a subquery if it is done.
My intention with this was to keep the signature of the methods in DBFilter as unified as possible while keeping the DatabaseImplementation as agnostic as possible to the details of PostgreSQL implementation.
An alternative I considered was to override the whole `QueryResources` method for calling specific functions of PostgreSQLFilter but it seems cleaner this way.
Also, my first approach was to check the whereClause already introduced in the selector, and I …
> Inequality filter

- test/integration/logging_test.go
- test/main.go
Resolves #953 
```release-note
NONE
```
The LOG_URL retrieves the logs in the expected order, but now we have a test that ensures that.
> Add a test to check the order of retrieved logs

- cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go
- cmd/sink/filters/filters.go
- cmd/sink/filters/filters_test.go
- cmd/sink/filters/namespace_gvk.go
- pkg/cel/cel.go
Related to #986 
```release-note
NONE
```
The sink current creates CEL expressions for `archiveWhen`, `deleteWhen`, and `archiveOnDelete` for namespaces as follow:
```
(< cel expression for ApiVersion and Kind from KubeArchiveConfig in namespace >) || (< cel expression from KubeArchiveConfig in the Kubearchive namespace for the same ApiVersion and Kind if it exists >)
```
This PR changes this so that CEL expression for the KubeArchiveConfig in the kubearchive namespace are compiled into a separate CEL program from the CEL expressions from other namespaces. Then the functions that determine if a resource should be archived check if there is a CEL expression for this namespace and if there is a global CEL expression, executes both and performs the or on their results
> separate global and local cel expressions

- pkg/database/sql/postgresql.go
- pkg/models/labels.go
- test/integration/labels_test.go
Resolves #1022  
```release-note
Fixed the "existence" label selector, now resources without labels are returned too.
```
* I had to change a query to include adding resources with empty labels, to mimic the Kubernetes API results. Should we check again with the DB expert on performance?
* `make([]string, 1)` was creating an slice with an empty string `[]string{""}` that was leading to some problems.
> Added integration tests for labelSelector

- cmd/operator/api/v1alpha1/clusterkubearchiveconfig_types.go
- cmd/operator/api/v1alpha1/clustervacuumconfig_types.go
- cmd/operator/api/v1alpha1/clustervacuumconfig_webhook.go
- cmd/operator/api/v1alpha1/clustervacuumconfig_webhook_test.go
- cmd/operator/api/v1alpha1/kubearchiveconfig_types.go
- cmd/operator/api/v1alpha1/namespacevacuumconfig_types.go
- cmd/operator/api/v1alpha1/namespacevacuumconfig_webhook.go
- cmd/operator/api/v1alpha1/namespacevacuumconfig_webhook_test.go
- cmd/operator/internal/controller/clusterkubearchiveconfig_controller.go
- cmd/operator/internal/controller/kubearchiveconfig_controller.go
- cmd/operator/main.go
- config/kustomization.yaml
- config/templates/operator/webhooks.yaml
Related to #991
A cluster vacuum is configured in the KubeArchive installation namespace.  It allows the KubeArchive administrator
to vacuum any or all namespaces that are configured for KubeArchive. The ClusterVacuumConfig resources is used 
to configure which resources should be vacuumed on a namespace level. The configuration follows the following
rules:
- If a namespace is configured with no resources, then all resources configured for KubeArchive in that namespace are vacuumed.
- If a namespace is configured with a list of resources, then only those resources specified under that namespace are vacuumed.
- The special namespace name "---all-namespaces---" indicates that all namespaces configured for KubeArchive should be vacuumed. This allow an easy way to indicate all namespaces and …
> Add NamespaceVacuumConfig and ClusterVacuumConfig resources.

- cmd/operator/api/v1alpha1/clusterkubearchiveconfig_types.go
- cmd/sink/k8s/client.go
- go.mod
- go.sum
- pkg/cloudevents/sink_publisher.go
Related to #991
```release-note
NONE
```
Here's a sample code snippet for using this new package to send a cloud event to the sink.
```
func main() {
namespacePtr := flag.String("namespace", "default", "Namespace to vacuum.")
slog.Info("Started publishing sink events", "namespace", *namespacePtr)
scep, err := cloudevents.NewSinkCloudEventPublisher("localhost:8080:/foo", "org.kubearchive.vacuum.update")
if err != nil {
slog.Error("Unable to create sink cloudevent publisher", "error", err)
return
}
selector := sourcesv1.APIVersionKindSelector{
APIVersion: "apps/v1",
Kind:       "Deployment",
}
result := scep.SendByAPIVersionKindSelector(context.Background(), *namespacePtr, &selector)
if !ce.IsACK(result) {
slog.Error("Unable to send cloudevent", "result", result)
return
} …
```
> Add sink cloudevent publisher.

- pkg/database/sql/reader.go
- test/integration/logging_test.go
Resolve #1027  
```release-note
Fixed bug where the API did not return logs if the annotation `kubectl.kubernetes.io/default-container` had an empty value. Now the API returns the first container of the pod instead.
```
* Simplified the related integration tests.
> Fix empty log annotation use-case

- cmd/api/routers/routers.go
Resolves #1082 
```release-note
NONE
```
> Fix panic recovered error on invalid label selectors

- config/kustomization.yaml
- config/templates/clusterroles.yaml
Resolves #1087 
```release-note
Added `kubearchive-edit` and `kubearchive-view` roles that get automatically aggregated to ClusterRoles `edit` and `view`.
```
* Roles are not aggregated to `admin` because by default `view` and `edit` are aggregated into `admin` automatically. Check the labels of those clusterroles on the cluster, they should have `rbac.authorization.k8s.io/aggregate-to-admin: "true"` themselves.
> Add aggregated ClusterRoles

- cmd/sink/filters/fake/filters.go
- cmd/sink/filters/filters.go
- cmd/sink/filters/filters_test.go
- cmd/sink/routers/routers.go
- docs/modules/ROOT/pages/configuration/observability.adoc
- pkg/observability/metrics.go
Resolves #1029 
```release-note
Added a new label value for `kubearchive.cloudevents.total` to identify cloudevents from resources that are not configured. Read the observability documentation for more information.
```
> Sink no configured resources

- go.mod
- pkg/cmd/get.go
- pkg/cmd/get_test.go
- pkg/cmd/testdata/expected_json_output.json
- pkg/cmd/testdata/expected_table_output.txt
- pkg/cmd/testdata/expected_yaml_output.yaml
Add output format for JSON, YAML and default table.
Assisted-by: Cursor
Resolves #299, related #288 
```release-note
NONE
```
The KubeArchive API doesn't support table format so in this PR I'm just going with the default parameters: `NAME` and `AGE`.
I used cursor to help me understand and implement how could we use the code and the printers already available
in kubectl to avoid repeating code while keeping shorter and with less functionality.
The code is a mix of their suggestions with my manual modifications.
The tests are more of a several iteration process but only code created by Cursor.
This is a PR that covers almost the same as https://github.com/kubearchive/kubearchive/pull/977.
I am creating it because I wanted to explore a different approach a tried to use more of the provided …
> Add output format on the cli - using kubectl approach

- cmd/operator/internal/controller/kubearchiveconfig_controller.go
Resolves #1218 
```release-note
Fixed a bug where the namespaces monitored by KubeArchive were updated without need, causing pressure on the Kubernetes API on a large number of namespaces.
```
When the Namespace is already in the correct shape, we can spare the request to the APIServer.
> avoid updating Namespaces if not needed

- .github/workflows/assign-reviewers.yml
- .github/workflows/copy-labels.yml
Assisted-by: Cursor AI
Resolves #1219  
```release-note
NONE
```
I've also updated the version of the action that add reviewers based on labels. The new version
has more debug messages that can help troubleshoot potential issues in the future.
I wasn't able to troubleshoot what was the problem in [here](https://github.com/kubearchive/kubearchive/actions/runs/16468223952/job/46642107193)
> Fix the set up PR for external contributors

- config/templates/api_server/api_server.yaml
- test/integration/impersonation_test.go
Resolves #1230 
```release-note
NONE
```
* I decided to use a default value for the AUTH_IMPERSONATE on the manifests, so we simplify a bit the test and we can go back to the previous state. WIthout the variable going back to the original state meant to delete the environment variable, which we didn't have a function for. Now we can reuse the `setImpersonation` function to achieve it.
> Fix impersonation test state handling

- .github/workflows/copy-labels.yml
- cmd/sink/routers/routers.go
- config/templates/sink/sink.yaml
Resolves #1233  
```release-note
NONE
```
Increase timeout for readyz because when the kubernetes api server is under pressure, it can take more than 1 second to respond. Switching from List to Get because Get is more performant
> increase timeout for sink readyz enpoint and use Get instead of List for SinkFilters

- DEVELOPMENT.md
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/cli/configuration.adoc
- go.mod
- pkg/cmd/cmd_test.go
- pkg/cmd/config/config.go
- pkg/cmd/config/config_test.go
- pkg/cmd/config/testdata/kubeconfig.yaml
- pkg/cmd/config/testdata/test-cert.crt
- pkg/cmd/get.go
- pkg/cmd/get_test.go
- pkg/cmd/logs.go
- pkg/cmd/logs_test.go
- pkg/cmd/testdata/expected_yaml_output.yaml
Assisted-by: Cursor AI
Resolves #1168 
```release-note
NONE
```
This was tested on development environment and on konflux staging:
```bash
kubectl get -n kubearchive secrets kubearchive-api-server-tls -o jsonpath='{.data.ca\.crt}' | base64 -d > ca.crt
KUBECTL_PLUGIN_ARCHIVE_SKIP_CERT=ca.crt KUBECTL_PLUGIN_ARCHIVE_TOKEN=$(kubectl create -n test token default) go run cmd/kubectl-archive/main.go get v1 pods -n test
go run cmd/kubectl-archive/main.go get v1 pods -n product-kubearchive --kubearchive-insecure-skip-tls-verify
KUBECTL_PLUGIN_ARCHIVE_HOST=https://kubearchive-api-server-product-kubearchive.apps.stone-stg-rh01.l2vh.p1.openshiftapps.com go run cmd/kubectl-archive/main.go get v1 pods -n product-kubearchive
```
I've refactored the code to use the flags provided by built-in kubectl and …
> Add kubectl archive config

- cmd/sink/filters/fake/filters.go
- cmd/sink/filters/fake/filters_test.go
- cmd/sink/filters/filters.go
- cmd/sink/filters/filters_test.go
- cmd/sink/filters/testdata/sf-archive-on-delete.yaml
- cmd/sink/filters/testdata/sf-archive.yaml
- cmd/sink/filters/testdata/sf-delete.yaml
- cmd/sink/routers/routers_test.go
Resolves #1293 
```release-note
NONE
```
Add a check in the sink when executing filters to make sure that resources that match the global filters only get written to the database if the resource is from a namespace that kubearchive is configured to watch.
> sink only writes resources to db from namespaces configured by users

- pkg/cloudevents/sink_publisher.go
Resolves #1235 
```release-note
Fixes a cryptic error raised by the vacuum container regarding a `nil` reference.
```
> Handle error when the broker has no URL

- cmd/api/discovery/apiresources.go
- cmd/api/discovery/apiresources_test.go
- cmd/api/main.go
- test/integration/integration_test.go
Resolves #1295 
```release-note
Changes response code when a resource does not exist in the cluster from 400 to 404.
```
> Return 404 when resource do not exist
