- .github/workflows/static_code_analysis.yml
- .github/workflows/yamllint.yml
- .yamllint.yml
- charts/kubearchive/Chart.yaml
- charts/kubearchive/crds/eventing-core.yaml
- charts/kubearchive/crds/eventing-crds.yaml
- charts/kubearchive/templates/api_server_source.yaml
- charts/kubearchive/templates/cluster_role.yaml
- charts/kubearchive/templates/cluster_role_binding.yaml
- charts/kubearchive/templates/namespace.yaml
- charts/kubearchive/templates/service_account.yaml
- charts/kubearchive/templates/sink.yaml
- charts/kubearchive/values.yaml
Adding yamllint scan as GitHub action for CI. Also updated the existing YAML files so they would pass the scan.
Signed-off-by: Chris Beer <cbeer@redhat.com>
> fix(KAR-32): add yamllint CI

- README.md
Modify the README.md to include instructions on testing the sink and updating the chart values.
> Add instructions to update chart values

- cmd/kubectl-archive/main.go
* Add a single entry-point file for the kubect plugin that KubeArchive will offer.
Fixes #10
> Add placeholder CLI file

- cmd/api/main.go
- go.mod
> change module name to follow standard naming scheme

- pkg/observability/trace.go
> utility functions for flushing spans and shutting down instrumentation

- cmd/api/auth/authz.go
- cmd/api/main.go
- cmd/api/main_test.go
- cmd/api/routers/routers_test.go
- go.mod
- go.sum
* Add struct with k8sclient and router.
* Created a test passing a fake k8sclient.
Close #27
> Use Server struct to share things

- README.md
- charts/kubearchive/templates/api_server.yaml
- charts/kubearchive/templates/role.yaml
- charts/kubearchive/templates/role_binding.yaml
- charts/kubearchive/templates/service_account.yaml
- charts/kubearchive/values.yaml
- cmd/api/auth/authz.go
- cmd/api/auth/authz_test.go
> Api server helm chart

- charts/kubearchive/templates/sink.yaml
- charts/kubearchive/values.yaml
> make number kubearchive-sink replicas configureable

- README.md
- charts/kubearchive/values.yaml
- cmd/sink/main.go
- go.mod
- go.sum
Until the stuff around the database is more solid, I have the sink logging cloud events to stderr
closes #33
> initial knative-eventing sink

- cmd/sink/main.go
- go.mod
- go.sum
Add basic OTel trace instrumentation to the sink and start it automatically
closes #38
> Add OTel trace instrumentation to sink

- charts/kubearchive/templates/sink.yaml
- charts/kubearchive/values.yaml
> set propper env var on sink to enable otel instrumentation

- MAINTAINERS.md
> docs: add MAINTAINERS.md file

- .github/workflows/static_code_analysis.yml
- .yamllint.yml
- charts/kubearchive/Chart.yaml
- ct.yaml
ct-lint includes:
- helm lint
- version checking
- YAML schema validation on Chart.yaml
- YAML linting for Chart.yaml and values.yaml
> Include ct-lint in the static_code_analysis workflow

- .github/workflows/renovate.yml
> Add manual trigger to Renovate job

- CONTRIBUTING.md
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/contributors/guide.adoc
> docs: add contribution guide

- charts/kubearchive/templates/api_server/certificates.yaml
* Fix the name for the certificate issuer
Closes #108
> fix: wrong name for certificate issuer

- charts/kubearchive/templates/test/kac.yaml
- cmd/operator/internal/controller/kubearchiveconfig_controller.go
Resolves https://github.com/kubearchive/kubearchive/issues/126.
Note that I am trying to figure out how to determine the plural correctly (rather than just appending "s").  Putting the PR out now just so if people need it.
> Fix issues with plurals and rolebinding.

- .github/workflows/go_test_integration.yml
- DEVELOPMENT.md
- hack/quick-install.sh
- test/integration/integration_test.go
* Deploy KubeArchive before starting the integration tests.
* Introduced a test that checks the deployments ready replicas.
Closes #129
> Add baseline for integration tests

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/reference/database.adoc
* Added reference section in the docs
* Added database schema document.
Fixes #163
> Document database schema

- .golangci.yml
- cmd/operator/internal/controller/kubearchiveconfig_controller.go
- cmd/operator/internal/controller/kubearchiveconfig_controller_test.go
* Add error handling for some functions on the Controller code.
* Skipped a problematic test.
Fixes #125
> Handle errors on the controller

- DEVELOPMENT.md
- charts/kubearchive/README.md
- charts/kubearchive/templates/_helpers.tpl
- charts/kubearchive/templates/api_server/api_server.yaml
- charts/kubearchive/templates/database/ps-claim.yaml
- charts/kubearchive/templates/database/ps-deployment.yaml
- charts/kubearchive/templates/database/ps-pv.yaml
- charts/kubearchive/templates/database/ps-secret.yaml
- charts/kubearchive/templates/database/ps-service.yaml
- charts/kubearchive/templates/sink/sink.yaml
- charts/kubearchive/values.yaml
- database/README.md
> chore: apply naming conventions to database resources in helm chart

- DEVELOPMENT.md
- cmd/api/main.go
- cmd/api/routers/routers.go
- cmd/api/routers/routers_test.go
- pkg/database/database.go
- pkg/database/database_test.go
- pkg/database/fake/dabatase_generated_test.go
- pkg/database/fake/database_generated.go
> Add endpoint to query non core namespaced resources

- .editorconfig
- DEVELOPMENT.md
- charts/kubearchive/README.md
- database/README.md
Fixes #57 
```release-note
NONE
```
Two separated commits:
* One with the .editorconfig file
* Other with some changes applied to the markdown files
NOTE: My IDE aditionally added some blank lines after headers. Let me know if that is ok for you. The editorconfig file
doesn't allow that kind of configuration. But I kept it as I think it makes raw markdown more readable.
NOTE2: I've included the property `max_line_length`. It's not supported by [all editors](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#supported-by-a-limited-number-of-editors), vscode doesn't support it [yet](https://developercommunity.visualstudio.com/t/support-max-line-length-in-editorconfig-for-visual/567214), neovim and all jetbrains editors do.
I included it because I think that there is …
> Add .editorconfig file

- charts/kubearchive/templates/api_server/certificates.yaml
- charts/kubearchive/templates/certificates.yaml
Fixes #105 
```release-note
NONE
```
> Apply Helm naming conventions to general templates

- .github/workflows/documentation-build.yaml
- .github/workflows/documentation-release.yaml
- .github/workflows/gitleaks.yml
- .github/workflows/go_test.yml
- .github/workflows/go_test_integration.yml
- .github/workflows/golangci_lint.yml
- .github/workflows/release.yml
- .github/workflows/renovate.yml
Updates the GitHub actions so they have consistent names and debug output when running. Also fixes an inconsistent version for "setup-go@v5", all the actions have been updated to use go-version "stable".
Fixes #203
```release-note
Updates GitHub actions for consistent action names, debug, and versions.
```
kind/documentation
> Consistent GitHub action names, debug, and versions

- cmd/operator/internal/controller/kubearchiveconfig_controller.go
Add new Role and RoleBinding for sink that allows it to delete resources in a namespace watched by `KubeArchive`
Resolves https://github.com/kubearchive/kubearchive/issues/219.
> Add new Role and RoleBinding for sink.

- charts/kubearchive/templates/test/kac.yaml
- cmd/operator/api/v1alpha1/kubearchiveconfig_types.go
- cmd/operator/internal/controller/kubearchiveconfig_controller.go
- docs/modules/ROOT/pages/configuration/kubearchiveconfig.adoc
Resolves https://github.com/kubearchive/kubearchive/issues/222.
> Enhance KubeArchiveConfig to support filtering.

- charts/kubearchive/templates/operator/operator.yaml
- cmd/operator/internal/controller/kubearchiveconfig_controller.go
Resolves https://github.com/kubearchive/kubearchive/issues/254.
> Designate ApiServerSource resources resources as such.

- README.md
- charts/kubearchive/templates/certificates.yaml
- docs/README.md
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/contributors/naming-conventions.adoc
Fixes #111
```release-note
Include naming conventions documentation for contributors.
```
Added the docs for the helm chart naming conventions.
Also added 3 other commits with little fixes:
* Added link to doc in general README
* Added language in code snippets
* Fix a variable reference in the certificates template of the helm chart
> Helm naming conventions docs

- docs/antora-playbook.yaml
Fixes #267
```release-note
Fix documentation header link
```
> Fix docs header link

- cmd/operator/internal/controller/kubearchiveconfig_controller.go
- go.mod
Fixes #221
```release-note
NONE
```
See details in https://github.com/kubearchive/kubearchive/issues/221.
> Operator creates and managers a filter ConfigMap

- test/integration/integration_test.go
Fixes #127 
```release-note
NONE
```
The integration test checks for the following objects in the test-<random-string> namespace.
- Deployment
- ReplicaSet
- Pod
- ApiServerSource
- EventType (add, delete, update).
For the ApiServerSource and the EventType objects, the status check is done by a kubectl command + jsonpath filtering.
> introduce the first integration test for the operator

- charts/kubearchive/templates/_helpers.tpl
- charts/kubearchive/templates/api_server/api_server.yaml
- charts/kubearchive/templates/sink/sink.yaml
- charts/kubearchive/templates/traces-collector.yaml
- charts/kubearchive/values.yaml
- go.mod
- go.sum
- pkg/observability/trace.go
Fixes #213 
```release-note
NONE
```
* This is still a Draft, looking to share the code but a lot of things need to be solved first. See the issue for more information.
> Add Jaeger deployment

- cmd/api/auth/authn.go
- cmd/api/auth/authz.go
- cmd/api/auth/authz_test.go
- cmd/api/discovery/apiresources.go
- cmd/api/discovery/apiresources_test.go
- cmd/api/main.go
Resolves #202 
```release-note
NONE
```
* The approach for testing (creating a RESTClient) has been inspired by code that tests the kubectl code. Its bulky, but gets the work done. I didn't look at it enough to see how to make it easier, if that is possible.
> Add instrumentation for HTTP client

- charts/kubearchive/templates/test/kac.yaml
- cmd/operator/api/v1alpha1/kubearchiveconfig_types.go
- docs/modules/ROOT/pages/configuration/kubearchiveconfig.adoc
- test/integration/integration_test.go
Fixes #283
```release-note
NONE
```
> Operator should use camel case for YAML key names.

- charts/kubearchive/templates/operator/sink_filters.yaml
Resolves #300
```release-note
NONE
```
> Operator needs to provide an empty sink-filters ConfigMap.

- charts/kubearchive/templates/operator/auth_proxy_client_clusterrole.yaml
- charts/kubearchive/templates/operator/auth_proxy_role.yaml
- charts/kubearchive/templates/operator/auth_proxy_role_binding.yaml
- charts/kubearchive/templates/operator/auth_proxy_service.yaml
- charts/kubearchive/templates/operator/kubearchiveconfig_editor_role.yaml
- charts/kubearchive/templates/operator/kubearchiveconfig_viewer_role.yaml
- charts/kubearchive/templates/operator/leader_election_role.yaml
- charts/kubearchive/templates/operator/leader_election_role_binding.yaml
- charts/kubearchive/templates/operator/monitor.yaml
- charts/kubearchive/templates/operator/operator.yaml
- charts/kubearchive/templates/operator/role_binding.yaml
- charts/kubearchive/templates/operator/service_account.yaml
- charts/kubearchive/templates/sink/sink.yaml
- charts/kubearchive/values.yaml
- cmd/operator/generate.sh
Fixes #103 
```release-note
NONE
```
Applied the naming conventions described in the linked issue.
Note the following:
* Some resource names have changed to remove redundant suffix
* The label `app.kubernetes.io/name` has been changed to `{{ .Release.Name }}. Based on [the docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) I believe this value makes more sense than the kind of the resource.
* As the values under the `kubearchive` section weren't used anymore I removed them
There is a line out of the scope of the issue (but related). I removed the namespace of the sink service as it should have been removed in [naming conventions PR for the sink](https://github.com/kubearchive/kubearchive/pull/135).
> Apply naming conventions for operator in chart

- DEVELOPMENT.md
- charts/kubearchive/templates/_helpers.tpl
- charts/kubearchive/templates/traces-collector.yaml
Resolves #295 and #294 
```release-note
NONE
```
> How to enable traces on development

- charts/kubearchive/templates/operator/certificates.yaml
- charts/kubearchive/templates/operator/operator.yaml
- charts/kubearchive/templates/operator/service.yaml
- charts/kubearchive/templates/operator/webhooks.yaml
- charts/kubearchive/values.yaml
- cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go
- cmd/operator/generate.sh
- cmd/operator/main.go
Resolves #311
```release-note
NONE
```
> Validate CEL expressions in KubeArchiveConfig.

- DEVELOPMENT.md
Resolves #344
```release-note
NONE
```
> Add yq requirement to the documentation.

- .ko.yaml
- cmd/api/main.go
- cmd/operator/main.go
- cmd/sink/main.go
- hack/release.sh
Resolves #290 
```release-note
NONE
```
> Add version and commit vars to components

- test/integration/integration_test.go
- test/main.go
Resolves #354
```release-note
NONE
```
> Refactor integration tests to use retries

- cmd/api/auth/authn.go
- cmd/api/auth/authz.go
- cmd/api/discovery/apiresources.go
- cmd/api/routers/routers_test.go
Resolves #363
```release-note
NONE
```
> Remove next() before return on middleware

- charts/kubearchive/templates/api_server/api_server.yaml
- charts/kubearchive/values.yaml
- cmd/api/auth/authn.go
- cmd/api/auth/authn_test.go
- cmd/api/auth/authz.go
- cmd/api/auth/authz_test.go
- cmd/api/main.go
- cmd/api/main_test.go
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/configuration/cache-expiration-time.adoc
- pkg/cache/cache.go
- pkg/cache/cache_test.go
Resolves #194 
```release-note
NONE
```
> Cache AuthN and AuthZ requests

- DEVELOPMENT.md
- charts/kubearchive/templates/api_server/api_server.yaml
- charts/kubearchive/templates/operator/operator.yaml
- charts/kubearchive/templates/operator/service.yaml
- charts/kubearchive/values.yaml
Resolves #324
```release-note
NONE
```
* Included a new parameter in operator values called `debug` to allow the debugging
* Refactored api-server deployment to have a more similar syntax in the args list to the operator deployment
* Moved `name` of the container in the template of the operator deployment to the top
> Add docs and update helm chart to allow  interactively debug operator

- cmd/api/main.go
- cmd/api/routers/routers.go
- cmd/api/routers/routers_test.go
- pkg/database/database.go
- pkg/database/database_test.go
- pkg/database/fake/database_generated.go
- pkg/database/fake/database_generated_test.go
Resolves #197
```release-note
NONE
```
Will add the List changes of the PR https://github.com/kubearchive/kubearchive/pull/359 when it's merged
> Add core resources endpoints

- .github/workflows/release.yml
- DEVELOPMENT.md
- charts/kubearchive/templates/_helpers.tpl
- charts/kubearchive/templates/api_server/api_server.yaml
- charts/kubearchive/templates/api_server/role_binding.yaml
- charts/kubearchive/templates/api_server/service_account.yaml
- charts/kubearchive/templates/certificates.yaml
- charts/kubearchive/templates/database/database.yaml
- charts/kubearchive/templates/database/database_secret.yaml
- charts/kubearchive/templates/namespace.yaml
- charts/kubearchive/templates/sink/sink.yaml
- charts/kubearchive/templates/test/kac.yaml
- charts/kubearchive/templates/test/namespace.yaml
- charts/kubearchive/templates/test/test-sa.yaml
- charts/kubearchive/values.yaml
- cmd/operator/generate.sh
- database/init_db.go
- docs/modules/ROOT/pages/contributors/release.adoc
- hack/install-database.sh
- hack/quick-install.sh
- hack/release.sh
- test/integration/integration_test.go
Resolves #277, resolves #278, may be related to #271
```release-note
NONE
```
* Enabled the database deployment by default for development, as the Helm chart is now development oriented I think it makes sense.
* Moved POSTGRES_URL to the secret, should I move the port too?
* Moved the testSA to its own file on the `test` folder so its easier to toggle.
* Removed braces rules: they are not needed anymore and they introduce artifacts in the resulting release YAML.
* Introduced the creation of a namespace for production, so we don't need to ask users to `kubectl create ns kubearchive`
> Release as single YAML

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/configuration/enable-observability.adoc
Resolves #261 
```release-note
NONE
```
* Called "observability" instead of "tracing" because now we support metrics too.
> Add observability documentation

- .golangci.yml
Resolves #365 
```release-note
NONE
```
> Add 'unparam' to Go linters

- charts/kubearchive/templates/api_server/api_server.yaml
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/getting-started/installation.adoc
Resolves #252 
```release-note
NONE
```
* The `kubectl rollout` feels a little weird, but I don't want to change that right now. We can followup in a different issue.
* If you reapply the `kubearchive.yaml` file, it overwrites the database secret. We may want to rethink how we want users to deal with that. We can followup in a different issue.
* I introduced `GIN_MODE` as it was pretty straightforward to do.
* I did a little conditional in the page to use the latest download link if the user is looking at the `main` version, otherwise it uses the versioned link. Its not ideal, but if we keep it small, its not that bad.
> Add installation docs

- .github/workflows/documentation-build.yaml
- .github/workflows/documentation-release.yaml
Resolves #383 
```release-note
NONE
```
* Added steps in the documentation build so we can check from PRs if the thing is generating correctly, set the retention to 1 to avoid flooding limits.
> Fix documentation workflow to publish tags

- .github/pull_request_template.md
Resolves #272
```release-note
NONE
```
> Change Fixes to Resolves

- pkg/cmd/get.go
- pkg/cmd/get_test.go
Resolves #296 
```release-note
NONE
```
* The way to specify resources will be addressed at #297
> Add namespace support to the CLI

- DEVELOPMENT.md
- test/logging/splunk/cluster-flow.yaml
- test/logging/splunk/cluster-output.yaml
- test/logging/splunk/install.sh
- test/logging/splunk/logging.yaml
- test/logging/splunk/standalone.yaml
Resolves #408
```release-note
NONE
```
> Install Splunk for testing.

- test/log-generators/cronjobs/cronjob.yaml
- test/log-generators/cronjobs/install.sh
Resolves #402
```release-note
NONE
```
> Add CronJob to generate log files.

- cmd/operator/api/v1alpha1/kubearchiveconfig_types.go
- cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go
- cmd/operator/internal/controller/kubearchiveconfig_controller.go
Resolves #424
```release-note
NONE
```
> Add archiveOnDelete to the KubeArchiveConfig custom resource.

- DEVELOPMENT.md
- charts/kubearchive/templates/test/test-sa.yaml
- charts/kubearchive/values.yaml
Resolves #143 
```release-note
NONE
```
> Move the test SA to the test namespace

- charts/kubearchive/templates/database/database_secret.yaml
Resolves #433 
```release-note
NONE
```
> Fix POSTGRES_PORT in the database secret

- cmd/api/routers/routers.go
Resolves #435 
```release-note
NONE
```
> Pass proper context to DB Ping

- .github/workflows/release.yml
- docs/modules/ROOT/pages/contributors/secret-rotation.adoc
Resolves #379 
```release-note
NONE
```
* Had to go with two weeks due to restrictions in cron's capabilities.
* Check the `if` logic for the job. I think my reasoning is right, but I want someone to double check.
* Changed from bullet list to description list to improve visuals.
> Release uses deploy SSH key

- test/log-generators/pipelines/cluster-role-binding.yaml
- test/log-generators/pipelines/cronjob.yaml
- test/log-generators/pipelines/event-listener.yaml
- test/log-generators/pipelines/install.sh
- test/log-generators/pipelines/kaconf.yaml
- test/log-generators/pipelines/pipeline.yaml
- test/log-generators/pipelines/role-binding.yaml
- test/log-generators/pipelines/service-account.yaml
- test/log-generators/pipelines/task.yaml
- test/log-generators/pipelines/trigger-template.yaml
Resolves #406
```release-note
NONE
```
> Create a Tekton Pipeline log generator.

- test/log-generators/cronjobs/cronjob.yaml
- test/log-generators/cronjobs/install.sh
Resolves #443
```release-note
NONE
```
> Update CronJob log generator to take namespace parameters.

- integrations/database/mysql/README.md
- integrations/database/mysql/create-user.sql
- integrations/database/mysql/install.sh
- integrations/database/mysql/kubearchive.sql
- integrations/database/mysql/mysql.yaml
- integrations/database/mysql/root-secret.yaml
Resolves #451
```release-note
NONE
```
> Install MySQL in development environment.

- integrations/database/mariadb/README.md
- integrations/database/mariadb/database.yaml
- integrations/database/mariadb/grant.yaml
- integrations/database/mariadb/install.sh
- integrations/database/mariadb/kubearchive.sql
- integrations/database/mariadb/mariadb.yaml
- integrations/database/mariadb/secret.yaml
- integrations/database/mariadb/user.yaml
- integrations/database/postgresql/kubearchive-user.yaml
Resolves #459
```release-note
NONE
```
This PR also contains a fix for a warning in `integrations/database/postgresql/kubearchive-user.yaml`.
> Install MariaDB in the development environment.

- .github/workflows/release.yml
Resolves #379 
```release-note
NONE
```
> Fix if/else expression on the release workflow

- DEVELOPMENT.md
- charts/kubearchive/templates/api_server/api_server.yaml
- charts/kubearchive/templates/operator/operator.yaml
- charts/kubearchive/templates/operator/service.yaml
- charts/kubearchive/values.yaml
- test/debug/debug-deploy.sh
- test/debug/patch-security-context.yaml
- test/debug/patch-service.yaml
Resolves #478
```release-note
NONE
```
I end up using the `jq` + `kubectl` apply after trying several approaches with `kubectl patch` but none seemed to fit very good.
Note that we want to remove the probe keys and that is difficult to do with `kubectl patch`.
I also replaced `apply` for `replace` in the `hack/kubearchive-install.sh` because if not, the services keep the `debug` port.
> Add a script for deploy in debug mode

- cmd/api/abort/abort.go
- cmd/api/main.go
- cmd/operator/main.go
- cmd/sink/filters/filters.go
- cmd/sink/main.go
- go.mod
- pkg/database/database.go
- pkg/database/database_test.go
- pkg/middleware/logging.go
- test/main.go
Resolves #423 
```release-note
NONE
```
* I removed the logger parameter forwarding in the sink and went with using the default logger. Its simpler. If we need to pass a logger for whatever reason, then we can add it again.
> Use slog on KubeArchive

- cmd/api/main.go
- cmd/sink/main.go
- pkg/database/database.go
- pkg/database/fake/database_generated.go
Resolves #322 
```release-note
NONE
```
> Close DB connections

- docs/modules/ROOT/pages/contributors/guide.adoc
Resolves #507 
```release-note
NONE
```
> Change Security Mailing List to Email

- integrations/database/postgresql/kubearchive.sql
Resolves #517 
```release-note
NONE
```
> Add JSON indexes for PostgreSQL.

- cmd/operator/main.go
Related to #307 
```release-note
NONE
```
* The operator generates a lot of traces to the leases endpoint.
* We did not instrument webhooks, the approach is different and will be taken care of in another issue.
* Some screenshots:
> Instrument Operator base client

- cmd/api/auth/authz.go
- cmd/api/auth/authz_test.go
Resolves #399
```release-note
NONE
```
> Perform SAR with get or list

- README.md
Resolves #
```release-note
NONE
```
> Add Slack Channel and other communication info

- integrations/database/mariadb/install.sh
Resolves #512 
```release-note
NONE
```
> Fix MariaDB deployment script

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/design/logging-integration.adoc
Resolves #437
```release-note
NONE
```
> Design KubeArchive logging integration.

- cmd/sink/filters/filters.go
- pkg/cel/cel.go
- pkg/log_urls/log_urls.go
- pkg/log_urls/log_urls_test.go
- pkg/log_urls/testdata/splunk-cm.json
- pkg/log_urls/testdata/splunk-test1-data.json
- pkg/log_urls/testdata/splunk-test2-data.json
Resolves #519
```release-note
NONE
```
> Generate log URLs from ConfigMap data.

- docs/modules/ROOT/pages/reference/database.adoc
- integrations/database/postgresql/kubearchive.sql
Resolves #448
```release-note
NONE
```
> Add log_url table to the database.

- cmd/api/pagination/pagination.go
- cmd/api/routers/routers.go
- cmd/api/routers/routers_test.go
- pkg/database/database.go
- pkg/database/database_test.go
- pkg/database/fake/database_generated.go
- pkg/database/fake/database_generated_test.go
- pkg/database/mariadb.go
- pkg/database/postgresql.go
Resolves #537
```release-note
NONE
```
Extra things:
* Fixed a block in one method regarding limit, continueToken and pagination
* Added propert `t.Run` to some subtests.
* Fixed some leftovers from pagination: removed limit == "" logic, as its never empty since we use a default.
* Default to some limit using `DefaultQuery`.
* Removed queries without limit, as there is always a limit.
> Merged QueryCoreResources and QueryResources

- cmd/api/auth/authz.go
- cmd/api/auth/authz_test.go
Resolves #502
```release-note
Fix bug when caching authorization on different requests for the same user
```
After thinking about it I've chosen to use the whole SAR spec as a string for the cache key ofauthorization
> Use the whole SAR spec as the key of the cache for authZ

- cmd/operator/generate.sh
- hack/kubearchive-install.sh
- hack/release.sh
Resolves #410 
```release-note
NONE
```
Testing:
- Deploy from scratch (this validates the change in the operator script and kuberachive-install.sh).
- release.sh using a fork.
> Use mktemp to generate tmp files in bash scripts

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/configuration/global-filters.adoc
Resolves #509 
```release-note
NONE
```
> Add documentation for global filters

- cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go
Resolves #352
```release-note
NONE
```
> Allow only one KubeArchiveConfig resource per namespace.

- integrations/database/postgresql/kubearchive.sql
- pkg/database/postgresql.go
Resolves #580 
```release-note
NONE
```
* Improved 3 orders of magnitude the query for all resources regardless of namespace. See the numbers here: https://github.com/kubearchive/kubearchive/issues/580#issuecomment-2432271648
* The version changed to 17 because it was released a few weeks ago and we agreed to with the latest possible while we are doing development.
> Improve PostgreSQL DB queries

- cmd/sink/filters/filters_test.go
Resolves #593 
```release-note
NONE
```
- `newMockWatcher` registers as a helper function
- `TestHandleUpdates` registers each of its tests as a sub-test with `t.Run`
- change variable name `testCases` -> `tests` as well as loop variable `tc` -> `tt` to be more consistent with other tests
> fix sink filter test setup

- cmd/api/pagination/pagination.go
- cmd/api/pagination/pagination_test.go
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/reference/api.adoc
- test/integration/integration_test.go
- test/main.go
Resolves #552 
```release-note
NONE
```
* I'm not so sure about the documentation part, I just needed a place where to add these things so I went for the reference one. I plan to add more "practical detail" about pagination on #480.
> Add tests and docs for pagination

- cmd/operator/api/v1alpha1/kubearchiveconfig_webhook.go
- docs/modules/ROOT/pages/configuration/global-filters.adoc
- docs/modules/ROOT/pages/configuration/kubearchiveconfig.adoc
Resolves #585
```release-note
NONE
```
> Force KubeArchiveConfig resource to be named 'kubearchive'.

- charts/kubearchive/templates/api_server/api_server.yaml
- charts/kubearchive/templates/api_server/certificates.yaml
- charts/kubearchive/templates/api_server/role.yaml
- charts/kubearchive/templates/api_server/role_binding.yaml
- charts/kubearchive/templates/api_server/service_account.yaml
- charts/kubearchive/templates/operator/auth_proxy_client_clusterrole.yaml
- charts/kubearchive/templates/operator/auth_proxy_role.yaml
- charts/kubearchive/templates/operator/auth_proxy_role_binding.yaml
- charts/kubearchive/templates/operator/auth_proxy_service.yaml
- charts/kubearchive/templates/operator/certificates.yaml
- charts/kubearchive/templates/operator/kubearchiveconfig_editor_role.yaml
- charts/kubearchive/templates/operator/kubearchiveconfig_viewer_role.yaml
- charts/kubearchive/templates/operator/leader_election_role.yaml
- charts/kubearchive/templates/operator/leader_election_role_binding.yaml
- charts/kubearchive/templates/operator/monitor.yaml
- charts/kubearchive/templates/operator/operator.yaml
- charts/kubearchive/templates/operator/role_binding.yaml
- charts/kubearchive/templates/operator/service.yaml
- charts/kubearchive/templates/operator/service_account.yaml
- charts/kubearchive/templates/operator/sink_filters.yaml
- charts/kubearchive/templates/operator/webhooks.yaml
- charts/kubearchive/templates/sink/role.yaml
- charts/kubearchive/templates/sink/role_binding.yaml
- charts/kubearchive/templates/sink/service_account.yaml
- charts/kubearchive/templates/sink/sink.yaml
- charts/kubearchive/values.yaml
- hack/kubearchive-install.sh
- hack/release.sh
Resolves #499 
```release-note
NONE
```
> Unify labels for KubeArchive components

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/getting-started/configuration.adoc
- docs/modules/ROOT/pages/getting-started/installation.adoc
- docs/modules/ROOT/pages/getting-started/kubearchive-api.adoc
- docs/modules/ROOT/pages/index.adoc
Resolves #480 
```release-note
NONE
```
* I fixed an error with the installation guide as well.
* The idea is that you start in `getting-started/installation` and that directs you to the next step which is about the API, and then that sends you to the configuration.
* The documents aim to provide a tutorial experience, not a fully detailed one. This is the entrypoint for beginners to KubeArchive. Experienced users will find other resources more advanced, currently on `/configuration` (tracing, global filters, etc.)
> Added docs related with usage

- integrations/database/mariadb/kubearchive.sql
Resolves #606 
```release-note
NONE
```
> Add `log_url` table to MariaDB

- docs/modules/ROOT/pages/index.adoc
- docs/modules/ROOT/pages/reference/api.adoc
Resolves #642 
```release-note
NONE
```
> Small fixes on the docs

- pkg/database/connection.go
Resolves #617 
```release-note
NONE
```
* With this we will get more metrics from the database.
> Fix DB instrumentation initialization

- charts/kubearchive/templates/logging/configmap.yaml
- charts/kubearchive/templates/logging/secret.yaml
- docs/modules/ROOT/pages/design/logging-integration.adoc
- docs/modules/ROOT/pages/integrations/logging.adoc
- integrations/logging/elasticsearch/cluster-flow.yaml
- integrations/logging/elasticsearch/install.sh
- integrations/logging/splunk/cluster-flow.yaml
- integrations/logging/splunk/install.sh
Resolves #647
```release-note
NONE
```
> Document and initiate new logging strategy to return log file content.

- test/integration/integration_test.go
Resolves #653 
```release-note
NONE
```
> Address intermittent failure on a test

- .github/workflows/performance.yml
- .gitignore
- integrations/observability/grafana/install.sh
- pkg/observability/trace.go
- test/performance/README.md
- test/performance/limits.gotemplate
- test/performance/locustfile.py
- test/performance/metrics/main.go
- test/performance/pod.json
- test/performance/requirements.txt
- test/performance/run.sh
- test/performance/stats/main.go
Related to #527 , #504 
```release-note
NONE
```
* Next steps are aggregating the results somehow from another place.
> Add basic performance test

- integrations/database/postgresql/kubearchive.sql
- integrations/database/postgresql/postgres.yaml
Resolves #654 
```release-note
NONE
```
> Change postgreSQL version to 16.2

- cmd/api/abort/abort.go
- cmd/api/auth/authn.go
- cmd/api/auth/authz.go
- cmd/api/discovery/apiresources.go
- cmd/api/pagination/pagination.go
- cmd/api/routers/routers.go
Resolves #536 
```release-note
NONE
```
> Refactor errors

- DEVELOPMENT.md
Related to #659 
```release-note
NONE
```
> Update Splunk related development instructions

- pkg/database/environment_test.go
Resolves #673 
```release-note
NONE
```
I also added an extra test.
> Replace os.Setenv with t.Setenv in the database environment tests

- cmd/api/main.go
Related to #521 and #556 
```release-note
The KubeArchive API now gracefully shuts down if the process receives a TERM or INTERRUPT signal (SIGTERM or SIGINT respectively).
```
* Handling here the API, as the sink is not migrated to Gin yet (#556)
* SIGINT is not emitted by Kubernetes, but its the interrupt signal so I think is just normal that we handle it as well.
* To test delete the API pod. In the logs you should see the different messages.
> Handle SIGTERM on the API

- cmd/operator/main.go
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/contributors/documentation.adoc
- docs/modules/ROOT/pages/contributors/release.adoc
- docs/modules/ROOT/pages/design/logging-integration.adoc
- docs/modules/ROOT/pages/getting-started/configuration.adoc
- docs/modules/ROOT/pages/integrations/logging.adoc
Resolves #293 
```release-note
NONE
```
> Add documentation style document

- charts/kubearchive/templates/api_server/api_server.yaml
- cmd/api/routers/routers.go
- cmd/api/routers/routers_test.go
- pkg/database/database.go
- pkg/database/database_test.go
- pkg/database/fake/database_generated.go
- pkg/database/fake/database_generated_test.go
Resolves #504 
```release-note
NONE
```
> Do not deserialize resources from the database

- cmd/api/main.go
- cmd/api/routers/routers.go
- cmd/api/routers/routers_test.go
- pkg/database/database.go
- pkg/database/database_test.go
- pkg/database/fake/database_generated.go
- pkg/database/fake/database_generated_test.go
Resolves #641 
```release-note
NONE
```
* Merged Database's `QueryNamespacedResources` and `QueryResources` so its more compact. I think the logic does not look bad in that case, let me know what do you think.
> Merge API handlers

- .github/workflows/go_test_integration.yml
- test/integration/integration_test.go
Resolves #752 
```release-note
NONE
```
I'm checking in this PR how consistent are failures and adding logs to know better what is happening under the hood.
> Fix integration test errors

- .github/workflows/documentation-release.yaml
Resolves #765 
```release-note
NONE
```
> Do not release docs on tags

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/design/decisions.adoc
Resolves #466 
```release-note
NONE
```
> Add decisions from the GDoc

- cmd/api/main.go
- cmd/operator/main.go
- cmd/sink/main.go
- cmd/sink/server/server.go
- config/templates/api_server/api_server.yaml
- config/templates/operator/operator.yaml
- config/templates/sink/sink.yaml
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/configuration/kubearchive-logs.adoc
- pkg/logging/logging.go
- pkg/middleware/logging.go
Resolves #797 
```release-note
KubeArchive deployments now support the environment 'LOG_LEVEL' to control the minimum logging level. Defaults to 'INFO'.
```
> Introduce LOG_LEVEL and log changes

- integrations/logging/splunk/install.sh
Resolves #809 
```release-note
NONE
```
> Fix timeout on splunk installation

- .github/workflows/go_test_integration.yml
- test/integration/database_test.go
- test/integration/integration_test.go
- test/integration/logging_test.go
- test/integration/pagination_test.go
- test/main.go
Resolves #768 
```release-note
NONE
```
* Moved some tests around since files were getting very long.
> Move logging integration test to its own func

- cmd/sink/routers/routers.go
- config/templates/sink/sink.yaml
Resolves #447 
```release-note
NONE
```
* Inverted an if/else which had just a log line in the else clause.
* Removed some intermediate logs to reduce the number, we can add them back as debug if we need them.
> More explicit sink log messages

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/getting-started/installation.adoc
- docs/modules/ROOT/pages/integrations/database.adoc
- integrations/database/postgresql/kubearchive.sql
- integrations/database/postgresql/postgres.yaml
Resolves #806, resolves #807 
```release-note
The documentation now contains a page that details the integration of KubeArchive with databases.
```
The `kubearchive.sql` was modified by `pg_dump`.
I followed the instructions in https://github.com/kubearchive/kubearchive/blob/main/integrations/database/postgresql/README.md
> Add database integration docs

- integrations/database/postgresql/kubearchive.sql
Resolves #826 
```release-note
NONE
```
> Change PostgreSQL timestamps to be 'with timezone'

- test/performance/metrics/main.go
Resolves #838 
```release-note
NONE
```
> Introduced retries for performance requests

- config/templates/eventing/brokers.yaml
Resolves #881 
```release-note
NONE
```
if all retries are exhausted, this reduces the time to reach the last retry from 8s to 2s
> switch to linear backoffPolicy

- hack/get-next-version.go
Resolves #734 
```release-note
NONE
```
> Handle error when PR does not have kind

- cmd/sink/routers/routers.go
Resolves #872 
```release-note
NONE
```
> Fix id value on sink log

- pkg/logging/logging.go
Resolves #684 
```release-note
NONE
```
* This should make it easier to locate where the log is coming from, with this change instead of searching for the string we have the exact location
> Add source information to logging

- test/integration/database_test.go
- test/integration/integration_test.go
- test/integration/logging_test.go
- test/integration/operator_test.go
- test/integration/pagination_test.go
- test/integration/run.sh
- test/main.go
Resolves #863
```release-note
NONE
```
Also refactored the integration tests and added some speed enhancements.
The current test run had the integration tests taking 78 seconds to run.
> Enhance operator tests.

- pkg/database/database.go
- pkg/database/database_test.go
- pkg/database/fake/database_generated.go
Resolves #933 
```release-note
NONE
```
> Fix testing specific db implementations

- integrations/database/postgresql/kubearchive.sql
Resolves #903 
```release-note
NONE
```
> Update label and annotation gin index

- .github/workflows/golangci_lint.yml
- cmd/operator/internal/controller/kubearchiveconfig_controller.go
- cmd/sink/filters/filters.go
- cmd/sink/filters/filters_test.go
- pkg/cel/cel.go
Resolves #910 
```release-note
NONE
```
> Fix GolangCI issues and schedule scan each month

- pkg/database/database.go
- pkg/database/database_test.go
- pkg/database/facade/filter.go
- pkg/database/facade/selector.go
- pkg/database/facade/sorter.go
- pkg/database/fake/database_generated.go
- pkg/database/fake/database_generated_test.go
- pkg/database/mariadb.go
- pkg/database/postgresql.go
Resolves #936 
```release-note
NONE
```
> Make resources not used outside its pkg unexported

- docs/modules/ROOT/pages/design/logging-integration.adoc
- docs/modules/ROOT/pages/integrations/logging.adoc
Resolves #775 
```release-note
NONE
```
> Update logging integration docs

- cmd/operator/internal/controller/kubearchiveconfig_controller.go
Resolves #961
```release-note
Fix logic error in operator when reconciling the ServiceAccount. 
```
> Fix logic error in operator when reconciling the ServiceAccount.

- test/performance/run.sh
Resolves #695 
```release-note
NONE
```
* Very small PR to start creating CSV reports for locust. When this change has been running for a week or so we can work on the other part: merging the requests CSV reports.
> Performance tests Locust CSV output

- pkg/cel/cel.go
Related to #986 
```release-note
NONE
```
This change for filters has memory going from 133.79MB to 1024.33KB.
Overall memory from 142.23MB down to 7.65MB.
These values based on the test case provided in #986.
> Create CEL environment one time.

- .github/workflows/go_test_integration.yml
- .github/workflows/performance.yml
- docs/modules/ROOT/pages/getting-started/installation.adoc
- hack/quick-install.sh
Resolves #970 
```release-note
Increased minimum version for Knative Eventing to v1.17.4 to avoid permissions problems.
```
* Increased minimum version of Knative Eventing to v1.17.4 to avoid that the APIServerSource requests permissions it does not need. Not really needed to work, so I'm not writing a Release Note of it, what do you think?
> Update Eventing to avoid permissions requests

- .github/workflows/golangci_lint.yml
- .golangci.yml
- cmd/api/logging/logging.go
- cmd/api/main.go
- cmd/api/main_test.go
- cmd/api/routers/routers.go
- cmd/operator/internal/controller/kubearchiveconfig_controller.go
- cmd/operator/test/utils/utils.go
- cmd/sink/filters/filters.go
- cmd/sink/k8s/client.go
- cmd/sink/logs/logs.go
- cmd/sink/routers/routers.go
- hack/get-next-version.go
- pkg/database/env/environment.go
- pkg/database/errors/errors.go
- pkg/database/fake/database_generated.go
- pkg/database/fake/database_generated_test.go
- pkg/database/sql/postgresql.go
- pkg/database/sql/reader.go
- pkg/database/sql/writer.go
- pkg/logging/logging.go
- pkg/logurls/logurls.go
- pkg/observability/trace.go
- test/integration/database_test.go
- test/integration/pagination_test.go
- test/main.go
Resolves #982 
```release-note
NONE
```
* Our configuration didn't have build tags, which it needs to lint the integration tests.
* GolangCI Lint has a new version and I did the migration. The configuration file was automigrated and then I added some configuration to ignore some new rules. Other new rules I adopted purely based on taste. Let me know.
* I organized these two changes in two commits.
> GolangCI Lint corrections and upgrade

- .github/assign_label_reviewers.yml
- .github/issue_template.md
- .github/pull_request_template.md
- .github/workflows/assign-reviewers.yml
- .github/workflows/check-labels.yml
- .github/workflows/copy-labels.yml
- .github/workflows/release.yml
Resolves #550, resolved #500
```release-note
NONE
```
I've created an issue template with the structure that we are using in general terms and the reminders to 
properly add the labels in the issue.
For the assignee to each label, I've used the ones that were discussed in the past and for some labels that I was not sure, I picked the two people that did/create more issues with the specific label.
Feel free to ask me to change them if you think you should be part of the ownership of one the labels or components.
Tested [here](https://github.com/maruiz93/hello-world-rpm/pull/2).
I needed to use a Personal Access Token (owned by KubeArchive) to get the `pull_request_target: labeled` trigger to work.
More information in [here](https://github.com/orgs/community/discussions/25565)
> Workflow for setting up the PR

- integrations/observability/prometheus-operator/README.md
- integrations/observability/prometheus-operator/install.sh
- integrations/observability/prometheus-operator/kustomization.yaml
- integrations/observability/prometheus-operator/monitoring-otel-collector.yaml
- integrations/observability/prometheus-operator/monitoring-servicemonitor.yaml
- integrations/observability/prometheus-operator/otel-collector-config.yaml
Resolves #992 
```release-note
NONE
```
> Add Prometheus Operator as an integration

- .github/workflows/assign-reviewers.yml
- .github/workflows/check-labels.yml
- .github/workflows/copy-labels.yml
Resolves #1031  
```release-note
NONE
```
this allows renovate bot PRs to skip some checks so that its PRs can automerge
> skip label, assignee, issue link CI actions for renovate PRs

- .github/pull_request_template.md
- docs/modules/ROOT/pages/contributors/release.adoc
Resolves #944 
```release-note
NONE
```
> Add rules for Release Notes

- .github/workflows/performance.yml
Resolves #789 
```release-note
NONE
```
* I forgot to add the `migrate` installation to the performance tests.
> Install migrate on performance tests

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/reference/vacuum.adoc
Resolves #991 
```release-note
Add vacuum documentation.
```
> Add cluster and namespace vacuum documentation.

- docs/modules/ROOT/nav.adoc
Resolves #991 
```release-note
NONE
```
> Fix vacuum documentation link.

- docs/modules/ROOT/nav.adoc
Resolves #991 
```release-note
NONE
```
> Fix vacuum link yet again.

- docs/modules/ROOT/pages/reference/vacuum.adoc
Resolves #991 
```release-note
NONE
```
> Fix context in bulleted list.

- cmd/operator/internal/controller/kubearchiveconfig_controller.go
Resolves #1063 
```release-note
NONE
```
> Add resources from ClusterKubeArchiveConfig to sink Role.

- hack/release.sh
Resolves #1056 
```release-note
NONE
```
> Remove kubearchive.sql from the release

- .github/workflows/go_test.yml
- .licenserc.json
- cmd/operator/generate.sh
- cmd/operator/internal/controller/clusterkubearchiveconfig_controller_test.go
- cmd/operator/internal/controller/common.go
- cmd/operator/internal/controller/kubearchiveconfig_controller.go
- cmd/operator/internal/controller/kubearchiveconfig_controller_test.go
- cmd/operator/internal/controller/suite_test.go
- cmd/operator/internal/controller/testdata/crds/apiserversource-crd.yaml
- cmd/operator/internal/controller/testdata/crds/broker.yaml
- pkg/constants/constants.go
- test/integration/operator_test.go
- test/main.go
Resolves #1061 
```release-note
NONE
```
> Add controller-runtime operator tests.

- pkg/constants/constants.go
Resolves #1078  
```release-note
Fixed an error in which KubeArchive was referring to its own components wrong.
```
> Fix constant names

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/configuration/delayed-deletes.adoc
- docs/modules/ROOT/pages/reference/vacuum.adoc
Resolves #906, resolves #951 
```release-note
Added documentation page about Delayed Deletes in the configuration section.
```
> Add doc entry about delayed deletes

- test/performance/merge.sh
- test/performance/merge/main.go
- test/performance/req.gnuplot
- test/performance/run.sh
Resolves #964 , resolves #862
```release-note
NONE
```
> Merge requests performance reports

- docs/modules/ROOT/pages/design/decisions.adoc
Resolves #986 
```release-note
NONE
```
* I wanted to have somewhere in our documentation information about the CEL expressions memory consumption, so I introduced this decision linking it to the issue.
> Add documentation regarding CEL expressions storage

- pkg/database/database.go
- pkg/database/database_test.go
- pkg/database/fake/database_generated.go
Resolves #1117 
```release-note
Adds a check to ensure the database schema is the proper one before starting up.
```
* I didn't include this where I should: #907 but there were no tests, so I didn't notice.
> Add DB check on startup

- .github/workflows/golangci_lint.yml
Resolves #1119
```release-note
NONE
```
> Add 'issues' permissions to the workflow

- cmd/sink/routers/routers.go
- pkg/database/fake/database_generated.go
- pkg/database/fake/database_generated_test.go
- pkg/database/interfaces/database.go
- pkg/database/sql/mariadb.go
- pkg/database/sql/mariadb_test.go
- pkg/database/sql/postgresql.go
- pkg/database/sql/postgresql_test.go
- pkg/database/sql/writer.go
Resolves #816 
```release-note
Changes resource archival to fail if KubeaArchive fails to write the logs.
```
> Inserting resources and logs are now a single transaction

- .github/workflows/go_test_integration.yml
- integrations/logging/loki/README.md
- integrations/logging/loki/install.sh
- integrations/logging/loki/manifests/cluster-output.yaml
- integrations/logging/loki/patch-logging-secret.yaml
- integrations/logging/loki/uninstall.sh
- integrations/logging/loki/values.grafana.yaml
- integrations/logging/loki/values.loki.yaml
- integrations/logging/loki/values.minio.yaml
- integrations/logging/loki/values.vector.yaml
Resolves #1089
Signed-off-by: Oleg Betsun <obetsun@redhat.com>
```release-note
NONE
```
```
No changes in the code were introduced.
```
> Add vector/loki integration

- DEVELOPMENT.md
- hack/quick-install.sh
- integrations/kafka/README.md
- integrations/kafka/config-br-defaults-kafka.yaml
- integrations/kafka/config-br-defaults.yaml
- integrations/kafka/install.sh
- integrations/kafka/kafka-broker-config.yaml
- integrations/kafka/uninstall.sh
Resolves #980
```release-note
NONE
```
Adds the following scripts and accompanying configuration:
- install script for strimzi + kafka cluster + knative eventing kafka extensions
- uninstall script to set kubearchive back to the MT channel based broker
This PR replaces #1076
> add kafka integration

- cmd/operator/main.go
Resolves #1176 
```release-note
Added `--leader-lease-duration` flag that accepts time-like strings such as `15s`, `2m`.
```
* I did use the default value as default, I can use a bigger duration by default.
> Add lease-duration flag

- docs/modules/ROOT/pages/configuration/observability.adoc
Resolves #1225 
```release-note
NONE
```
> Improve documentation regarding kubearchive.cloudevents.total

- cmd/api/main.go
- cmd/sink/server/server.go
Resolves #1191 
```release-note
Removes `gin.errors` from metrics as it can cause problems due to its unbound nature.
```
> Reduce otelgin metrics series

- docs/modules/ROOT/pages/integrations/database.adoc
Resolves #1236  
```release-note
NONE
```
> Fix links in docs

- cmd/sink/filters/filters.go
- cmd/sink/routers/routers.go
- pkg/cel/cel.go
- pkg/logging/logging.go
- pkg/logurls/logurls.go
Resolves #1269 
```release-note
Adds OpenTelemetry spans to various functions executed in the KubeArchive Sink to improve observability.
```
Traces will look like this now:
> Create spans on Sink functions

- cmd/kubectl-ka/main.go
- pkg/cmd/config/config.go
- pkg/cmd/config/config_test.go
- pkg/cmd/get.go
- pkg/cmd/get_test.go
- pkg/cmd/logs.go
- pkg/cmd/logs_test.go
Assisted-by: Cursor AI
Resolves #1248  
```release-note
NONE
```
> Rename kubectl-archive to kubectl-ka

- .github/workflows/go_test.yml
- .github/workflows/go_test_integration.yml
- .github/workflows/golangci_lint.yml
- .github/workflows/performance-recap.yml
- .github/workflows/performance.yml
- .github/workflows/release.yml
- .github/workflows/static_code_analysis.yml
- go.mod
- go.sum
- pkg/database/sql/mariadb_test.go
- pkg/database/sql/postgresql_test.go
- renovate.json
Resolves #1145 
```release-note
NONE
```
downgrade `gomega` to `v1.38.0` and renovate package rule to prevent upgrade to `v1.38.1`, which requires `go1.24`. Also changed the workflows to specify `go1.23.9` so that in the future, actions that upgrade the go version will fail. This will require us to manually increment the go version in the future.
> downgrade to go1.23

- integrations/logging/loki/values.loki.yaml
- test/integration/logging_test.go
Resolves #1342 
```release-note
NONE
```
> Disable detected_level label in loki

- config/kustomization.yaml
- config/templates/database/migration_job.yaml
- docs/modules/ROOT/pages/getting-started/installation.adoc
- hack/kubearchive-install.sh
- hack/release.sh
Resolves #1237 
```release-note
NONE
```
* Added Job but not using it. This is because I found some conflicts with our development way to install, I didn't want to change it substantially.
> Introduce migration job

- pkg/cloudevents/sink_publisher.go
Resolves #1135 
```release-note
NONE
```
> Fix sink publisher to reuse local resources.
